name: tutorials2
channels:
  - defaults
dependencies:
  - certifi=2018.4.16
  - pip=10.0.1
  - python=3.5.5
  - setuptools=39.2.0
  - vc=14.1
  - vs2015_runtime=15.5.2
  - wheel=0.31.1
  - wincertstore=0.2
